services:
  backend:
    image: johnnykg/snake-backend
    container_name: snake-backend
    restart: always
    networks:
      - snake-net
    ports:
      - '5000:5000'

  frontend:
    image: johnnykg/snake-frontend
    container_name: snake-frontend
    restart: always
    networks:
      - snake-net
    ports:
      - '80:80'

networks:
  snake-net:
    name: snake-net
    enable_ipv6: false
    driver: bridge
