services:
  backend:
    image: johnnykg/snake-backend
    container_name: snake-backend
    restart: always
    networks:
      - snake-net
    ports:
      - '5000:5000'

  nginx:
    image: johnnykg/snake-frontend
    container_name: snake-frontend
    restart: always
    networks:
      - snake-net
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  snake-net:
    name: snake-net
    enable_ipv6: false
    driver: bridge
