name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  EC2-DEPLOY:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.4
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: {{ secrets.AWS_SECRET_ACCES_KEY_SANDBOX }}
        aws_default_region: sa-east-1

        app_port:3000