name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Copy files with sssh
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY:  ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rltgoDzvo --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"
